package vista;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Habitats;
import controlador.Controlador_habitats;
import java.util.ArrayList;
import javax.swing.JCheckBox;
/**
 * Frame Habitats_vista que me permite visualizar gráficamente el crud de la clase Habitats
 *
 * @author Diego
 * @version 1.0
 */
public class Habitats_vista extends javax.swing.JInternalFrame {
/**
 * Variables Globales
 */
    int mod;
    private List<Habitats> tareas;
    private static int bandera_encontrado = 0;
    private static int bandera_buscar = 0;
    public static int bandera_hab_orden = 0;
    private static int bandera_crear_editar = 0;
/**
 * Constructor del Frame
 */
    public Habitats_vista() {
        initComponents();
        txtDe.setEditable(false);
        txtNc.setEditable(false);
        txtNe.setEditable(false);
        JCheckBox[] chb_i = {chb_1, chb_2, chb_3, chb_4, chb_5, chb_6};
        for (JCheckBox chb_i1 : chb_i) {
            chb_i1.setEnabled(false);
        }
        elemento_guardar.setEnabled(false);
        btn_cancelar.setEnabled(false);
        this.cargar_lista_de_tareas();
    }
/**
 * Método que me permite cargar en una tabla los datos de los hábitats
 */
    private void cargar_lista_de_tareas() {
        try {
            this.tareas = Controlador_habitats.cargarArbol();
            DefaultTableModel dtm = (DefaultTableModel) elemento_tabla.getModel();
            dtm.setRowCount(0);

            for (int i = 0; i < this.tareas.size(); i++) {
                String all_cont = "";
                for (int j = 0; j < this.tareas.get(i).getContinente().length; j++) {
                    all_cont += this.tareas.get(i).getContinente()[j] + " ";

                }

                dtm.addRow(new Object[]{
                    this.tareas.get(i).getNombreHab(),
                    this.tareas.get(i).getClima(),
                    this.tareas.get(i).getTipoVeg(),
                    all_cont

                });
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Ha surgido un error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        btnbuscar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        elemento_tabla = new javax.swing.JTable();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        elemento_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        txtDe = new javax.swing.JTextField();
        chb_1 = new javax.swing.JCheckBox();
        chb_3 = new javax.swing.JCheckBox();
        chb_4 = new javax.swing.JCheckBox();
        chb_2 = new javax.swing.JCheckBox();
        chb_5 = new javax.swing.JCheckBox();
        chb_6 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        cb_ordenar = new javax.swing.JComboBox();
        cb_crud = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        jLabel5.setText("Busqueda por");

        jCheckBox2.setText("jCheckBox1");

        setClosable(true);
        setIconifiable(true);
        setTitle("Hábitats");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        elemento_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre hábitat", "Clima", "Tipo de Vegetación", "Continente(s)       "
            }
        ));
        elemento_tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane1.setViewportView(elemento_tabla);

        jTabbedPane1.addTab("Listado", jScrollPane1);

        jLabel1.setText("Nombre del hábitat");

        jLabel2.setText("Clima");

        jLabel4.setText("Descripción");

        elemento_guardar.setText("Guardar");
        elemento_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elemento_guardarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        chb_1.setText("América");

        chb_3.setText("África");

        chb_4.setText("Asia");

        chb_2.setText("Europa");

        chb_5.setText("Oceanía");

        chb_6.setText("Antártida");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDe)
                            .addComponent(txtNc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chb_1)
                                            .addComponent(chb_2)
                                            .addComponent(chb_3))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chb_4)
                                            .addComponent(chb_5)
                                            .addComponent(chb_6))
                                        .addGap(10, 10, 10)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(125, 125, 125))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(elemento_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cancelar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chb_1)
                    .addComponent(chb_4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chb_2)
                    .addComponent(chb_5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chb_3)
                    .addComponent(chb_6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elemento_guardar)
                    .addComponent(btn_cancelar))
                .addGap(208, 208, 208))
        );

        jTabbedPane2.addTab("Insertar/Modificar", jPanel1);

        jLabel3.setText("Nombre del hábitat:");

        cb_ordenar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "nombre Ascendente", "nombre Descendente", "clima Ascendente", "clima Descendente" }));
        cb_ordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ordenarActionPerformed(evt);
            }
        });

        cb_crud.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Crear", "Editar", "Listar", "Eliminar" }));
        cb_crud.setSelectedIndex(2);
        cb_crud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_crudActionPerformed(evt);
            }
        });

        jLabel6.setText("Ordenar por:");

        jLabel7.setText("¿Qué operación desea realizar?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(20, 103, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                            .addComponent(cb_ordenar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jTabbedPane1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_crud, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbuscar)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_crud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

        try {

            bandera_encontrado = 0;
            if (!txtbuscar.getText().isEmpty()) {
                bandera_buscar = 1;
                this.tareas = Controlador_habitats.recuperarPorId(txtbuscar.getText());
                if (!tareas.isEmpty()) {
                    bandera_encontrado = 1;

                    DefaultTableModel dtm = (DefaultTableModel) elemento_tabla.getModel();
                    dtm.setRowCount(0);
                    for (int i = 0; i < this.tareas.size(); i++) {
                        String all_cont = "";
                        for (int j = 0; j < this.tareas.get(i).getContinente().length; j++) {
                            all_cont += this.tareas.get(i).getContinente()[j] + " ";

                        }
                        dtm.addRow(new Object[]{
                            this.tareas.get(i).getNombreHab(),
                            this.tareas.get(i).getClima(),
                            this.tareas.get(i).getTipoVeg(),
                            all_cont

                        });
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No se ha encontrado ninguna coincidencia\nPuede insertar la nueva especie ahora");
                }

            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Ha surgido un error y no se han podido recuperar los registros");
        }


    }//GEN-LAST:event_btnbuscarActionPerformed

    private void elemento_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elemento_guardarActionPerformed

        if (mod == 1) {
            //------------------mi forma de conseguir los items de continentes que ha seleccionado un usuario
            JCheckBox[] chb_i = {chb_1, chb_2, chb_3, chb_4, chb_5, chb_6}; //creo un array de tipo JCheckBox con mis 6 items
            ArrayList continentes = new ArrayList(); //creo una lista de contientes para almacenar solo los items q el usuario eligió
            for (int i = 0; i < chb_i.length; i++) { //voy recorriendo los items 
                if (chb_i[i].isSelected()) { //compruebo q cada item haya sido seleccionado
                    continentes.add(chb_i[i].getText()); //voy añadiendo a mi lista los items q el usuario eligió
                }
            }
            String[] cont_select = new String[continentes.size()]; // creo un array de string tal como lo defini en el pojo de habitats
            //convierto la lista en un array normalito 
            for (int i = 0; i < continentes.size(); i++) { //recorro la lista de contientes   
                cont_select[i] = (String) continentes.get(i); //almaceno en cada posición de mi array el elemnto  q existe en la lista de contientes
            }
            //---------------------fin de mi forma
            Controlador_habitats.editar(txtNe.getText(), txtNc.getText(), txtDe.getText(), cont_select);
            System.out.println(txtNe.getText());
            txtNe.setText("");
            txtNc.setText("");
            txtDe.setText("");
            txtDe.setEditable(false);
            txtNc.setEditable(false);
            txtNe.setEditable(false);

            for (JCheckBox chb_i1 : chb_i) {
                chb_i1.setSelected(false);
                chb_i1.setEnabled(false);
            }
            elemento_guardar.setEnabled(false);
            btn_cancelar.setEnabled(false);
            cb_crud.setEnabled(true);
            bandera_crear_editar = 0;
            cargar_lista_de_tareas();
        } else {
            if (!txtNe.getText().isEmpty()) {

                int ban_repetido = 0;
                this.tareas = Controlador_habitats.cargarArbol();
                for (Habitats tarea : tareas) {

                    if (txtNe.getText().equalsIgnoreCase(tarea.getNombreHab())) {

                        ban_repetido = 1;
                    }
                }
                if (ban_repetido == 0) {
                    this.guardar();
                    txtNe.setText("");
                    txtNc.setText("");
                    txtDe.setText("");
                    txtDe.setEditable(false);
                    txtNc.setEditable(false);
                    txtNe.setEditable(false);
                    JCheckBox[] chb_i = {chb_1, chb_2, chb_3, chb_4, chb_5, chb_6};

                    for (JCheckBox chb_i1 : chb_i) {
                        chb_i1.setSelected(false);
                        chb_i1.setEnabled(false);
                    }
                    elemento_guardar.setEnabled(false);
                    btn_cancelar.setEnabled(false);
                    cb_crud.setEnabled(true);
                    bandera_crear_editar = 0;
                } else {
                    JOptionPane.showMessageDialog(null, "La especie ya existe");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Ingrese el primer campo al menos");
            }

        }

    }//GEN-LAST:event_elemento_guardarActionPerformed

    private void cb_crudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_crudActionPerformed
        try {
            switch (cb_crud.getSelectedItem().toString()) {
                case "Crear":

                    if (bandera_encontrado == 0 && bandera_buscar == 1) {
                        txtDe.setEditable(true);
                        txtNc.setEditable(true);
                        txtNe.setEditable(true);
                        JCheckBox[] chb_i = {chb_1, chb_2, chb_3, chb_4, chb_5, chb_6};
                        for (JCheckBox chb_i1 : chb_i) {
                            chb_i1.setEnabled(true);
                        }
                        elemento_guardar.setEnabled(true);
                        btn_cancelar.setEnabled(true);
                        elemento_guardar.setText("Insertar");
                        cb_crud.setEnabled(false);
                        bandera_buscar = 0;
                        bandera_crear_editar = 1;
                        mod = 0;
                    }

                    break;
                case "Editar":

                    if (bandera_encontrado == 1 && bandera_buscar == 1) {

                        txtNc.setEditable(true);
                        txtDe.setEditable(true);
                        JCheckBox[] chb_i = {chb_1, chb_2, chb_3, chb_4, chb_5, chb_6};

                        for (JCheckBox chb_i1 : chb_i) {
                            chb_i1.setEnabled(true);
                        }

                        elemento_guardar.setEnabled(true);
                        elemento_guardar.setText("Guardar");
                        btn_cancelar.setEnabled(true);
                        cb_crud.setEnabled(false);

                        Habitats es = this.tareas.get(0);

                        txtNe.setText(es.getNombreHab());
                        txtNc.setText(es.getClima());
                        txtDe.setText(es.getTipoVeg());
//------------------mi forma de conseguir los items almacenados de respecitvo usuario
                        String[] cont_selec = es.getContinente();

                        for (int i = 0; i < chb_i.length; i++) {
                            for (int j = 0; j < cont_selec.length; j++) {
                                if (chb_i[i].getText().equals(cont_selec[j])) {
                                    chb_i[i].setSelected(true);
                                }
                            }
                        }
//*-----------------------------------
                        mod = 1;
                        bandera_buscar = 0;
                        bandera_crear_editar = 1;
                    }

                    break;
                case "Listar":
                    this.cargar_lista_de_tareas();

                    bandera_buscar = 0;
                    break;

                case "Eliminar":
                    if (bandera_encontrado == 1 && bandera_buscar == 1) {

                        String idc = (String) elemento_tabla.getValueAt(0, 0);

                        tareas = Controlador_habitats.eliminar(idc);
                        DefaultTableModel dtm = (DefaultTableModel) elemento_tabla.getModel();
                        dtm.setRowCount(0);
                        for (int i = 0; i < this.tareas.size(); i++) {
                            String all_cont = "";
                            for (int j = 0; j < this.tareas.get(i).getContinente().length; j++) {
                                all_cont += this.tareas.get(i).getContinente()[j] + " ";

                            }
                            dtm.addRow(new Object[]{
                                this.tareas.get(i).getNombreHab(),
                                this.tareas.get(i).getClima(),
                                this.tareas.get(i).getTipoVeg(),
                                all_cont

                            });
                        }
                    }

                    bandera_buscar = 0;
                    break;
                default:
                    bandera_buscar = 0;
                    System.out.println("Listar");
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_cb_crudActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        txtNe.setText("");
        txtNc.setText("");
        txtDe.setText("");
        JCheckBox[] chb_i = {chb_1, chb_2, chb_3, chb_4, chb_5, chb_6};

        for (JCheckBox chb_i1 : chb_i) {
            chb_i1.setSelected(false);
            chb_i1.setEnabled(false);
        }
        txtDe.setEditable(false);
        txtNc.setEditable(false);
        txtNe.setEditable(false);
        elemento_guardar.setEnabled(false);
        btn_cancelar.setEnabled(false);
        cb_crud.setEnabled(true);
        bandera_crear_editar = 0;

        cargar_lista_de_tareas();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void cb_ordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ordenarActionPerformed
        switch (cb_ordenar.getSelectedItem().toString()) {
            case "nombre Ascendente":
                try {
                    //revisar si ocurre bug en el ordenamiento es por esta condición
                    if ((bandera_buscar == 0 || bandera_encontrado == 0) && bandera_crear_editar == 0) {

                        this.tareas = Controlador_habitats.ordenarAsc();
                    }

                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                    JOptionPane.showMessageDialog(this, "Ha surgido un error y no se han podido recuperar los registros");
                }
                break;
            case "nombre Descendente":

                try {
                    if ((bandera_buscar == 0 || bandera_encontrado == 0) && bandera_crear_editar == 0) {
                        this.tareas = Controlador_habitats.ordenarDes();
                    }
                } catch (Exception ex) {
                    System.out.println(ex.getMessage());
                    JOptionPane.showMessageDialog(this, "Ha surgido un error y no se han podido recuperar los registros");
                }
                break;
            case "clima Ascendente":
                if ((bandera_buscar == 0 || bandera_encontrado == 0) && bandera_crear_editar == 0) {
                    bandera_hab_orden = 1;
                    this.tareas = Controlador_habitats.ordenarAsc();
                    bandera_hab_orden = 0;
                }
                break;
            case "clima Descendente":
                if ((bandera_buscar == 0 || bandera_encontrado == 0) && bandera_crear_editar == 0) {
                    bandera_hab_orden = 1;
                    this.tareas = Controlador_habitats.ordenarDes();
                    bandera_hab_orden = 0;
                }
                break;
            default:

        }
        DefaultTableModel dtm = (DefaultTableModel) elemento_tabla.getModel();
        dtm.setRowCount(0);
        for (int i = 0; i < this.tareas.size(); i++) {
            String all_cont = "";
            for (int j = 0; j < this.tareas.get(i).getContinente().length; j++) {
                all_cont += this.tareas.get(i).getContinente()[j] + " ";

            }
            dtm.addRow(new Object[]{
                this.tareas.get(i).getNombreHab(),
                this.tareas.get(i).getClima(),
                this.tareas.get(i).getTipoVeg(),
                all_cont

            });
        }

    }//GEN-LAST:event_cb_ordenarActionPerformed
    /**
     * Método que me permite guardar los datos de un hábitat a través de la vista
     */
    private void guardar() {
        String nombre_hab = txtNe.getText();
        String clima = txtNc.getText();
        String tipoVeget = txtDe.getText();
        //------------------mi forma de conseguir los items de continentes que ha seleccionado un usuario
        JCheckBox[] chb_i = {chb_1, chb_2, chb_3, chb_4, chb_5, chb_6}; //creo un array de tipo JCheckBox con mis 6 items
        ArrayList continentes = new ArrayList(); //creo una lista de contientes para almacenar solo los items q el usuario eligió
        for (int i = 0; i < chb_i.length; i++) { //voy recorriendo los items 
            if (chb_i[i].isSelected()) { //compruebo q cada item haya sido seleccionado
                continentes.add(chb_i[i].getText()); //voy añadiendo a mi lista los items q el usuario eligió
            }
        }
        String[] cont_select = new String[continentes.size()]; // creo un array de string tal como lo defini en el pojo de habitats
        //convierto la lista en un array normalito 
        for (int i = 0; i < continentes.size(); i++) { //recorro la lista de contientes   
            cont_select[i] = (String) continentes.get(i); //almaceno en cada posición de mi array el elemnto  q existe en la lista de contientes
        }
        //---------------------fin de mi forma
        Controlador_habitats.guardarArbol(nombre_hab, clima, tipoVeget, cont_select);
        System.out.println("");
        cargar_lista_de_tareas();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox cb_crud;
    private javax.swing.JComboBox cb_ordenar;
    private javax.swing.JCheckBox chb_1;
    private javax.swing.JCheckBox chb_2;
    private javax.swing.JCheckBox chb_3;
    private javax.swing.JCheckBox chb_4;
    private javax.swing.JCheckBox chb_5;
    private javax.swing.JCheckBox chb_6;
    private javax.swing.JButton elemento_guardar;
    private javax.swing.JTable elemento_tabla;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField txtDe;
    private javax.swing.JTextField txtNc;
    private javax.swing.JTextField txtNe;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
